language: java
jdk:
  - openjdk8
dist: xenial
sudo: true
branches:
  only:
    - master
    - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install:
  - ./gradlew --console plain assemble -x signArchives
jobs:
  include:
    - stage: Tests
      name: Unit & Integration Tests
      script:
        - ./gradlew --console plain test --info
        - sudo sysctl fs.inotify.max_user_watches=524288
        - sudo sysctl -p
        - git clone --depth 1 https://github.com/streamr-dev/streamr-docker-dev.git
        - sudo ifconfig docker0 10.200.10.1/24
        - $TRAVIS_BUILD_DIR/streamr-docker-dev/streamr-docker-dev/bin.sh start mysql redis engine-and-editor cassandra parity-node0 parity-sidechain-node0 bridge data-union-server broker-node-storage-1 broker-node-no-storage-1 broker-node-no-storage-2 nginx smtp
          #- $TRAVIS_BUILD_DIR/streamr-docker-dev/streamr-docker-dev/bin.sh log -f engine-and-editor broker-node-storage-1 broker-node-no-storage-1 broker-node-no-storage-2 &
        - $TRAVIS_BUILD_DIR/streamr-docker-dev/streamr-docker-dev/bin.sh wait
        - ./gradlew --console plain integrationTest --info
#  - stage: Tests
#    name: Cross-client tests
#    script:
#    - ".travis_scripts/cross-client-tests.sh"
