name: Check Gradle Version

on:
  push:
    branches:
      - dev-upgrade-gradle

jobs:
  build:
    name: Upgrade Gradle
    strategy:
      fail-fast: false # run all parallel jobs
      matrix:
        gradle:
          - 6.7      # latest version
          - 6.6.1
          - 6.5.1
          - 6.4.1
          - 6.3
          - 6.2.2
          - 6.1.1
          - 6.0.1
          - 5.6.4
          - 5.5.1
          - 5.4.1
          - 5.3.1
          - 5.2.1
          - 5.1.1
          - 4.10.3
          - 4.9
          - 4.8.1
          - 4.7
          - 4.6
          - 4.5.1
          - 4.4.1
          - 4.3.1
          - 4.3
          - 4.2.1
          - 4.1
          - 4.0.2
          - 3.5.1
          - 3.4.1
          - 3.3
          - 3.2.1
          - 3.1      # current version
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
          gradle-version: ${{ matrix.gradle }}

