name: Pull Request

on:
  pull_request:

jobs:
  build:
    name: Build PR
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Xmx6g -Xms4g
    steps:
      - name: Checkout Streamr Client Java
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build
        run: ./gradlew assemble -x signArchives
      - name: Unit Test
        run: ./gradlew test --stacktrace --info
      - name: Checkout Streamr Docker Dev
        uses:  actions/checkout@v2
        with:
          repository: streamr-dev/streamr-docker-dev
          path: streamr-docker-dev
      - name: Set up Linux
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl -p
          sudo ifconfig docker0 10.200.10.1/24
      - name: Start Streamr Docker Stack
        run: |
          ./streamr-docker-dev/bin.sh start mysql redis engine-and-editor cassandra parity-node0 parity-sidechain-node0 bridge data-union-server broker-node-storage-1 broker-node-no-storage-1 broker-node-no-storage-2 nginx smtp
          #./streamr-docker-dev/bin.sh log -f engine-and-editor broker-node-storage-1 broker-node-no-storage-1 broker-node-no-storage-2 &
          ./streamr-docker-dev/bin.sh wait
        working-directory: streamr-docker-dev
      - name: Integration Test
        run: ./gradlew integrationTest --stacktrace --info

